[workspace]
members = [
  "packages/core",
  "packages/app_helper",
  "crates/msauth",
  "crates/java",
  "crates/minecraft"
]

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = "symbols"
